<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ValheimWorldSync</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ValheimWorldSync.Infrastructure/ValheimWorldSync.Infrastructure.csproj" />
    <ProjectReference Include="../ValheimWorldSync.Platform.Windows/ValheimWorldSync.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
