<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ValheimWorldSync.Core/ValheimWorldSync.Core.csproj" />
    <ProjectReference Include="../ValheimWorldSync.Infrastructure/ValheimWorldSync.Infrastructure.csproj" />
  </ItemGroup>
</Project>
